version: '3'
services:
  api:
    image: node-docker-backend
    networks:
      - backend
    ports:
      - "3000:3000"

  web:
    image: node-docker-frontend
    networks:
      - backend
    ports:
      - "4200:4200"

networks:
  backend:
    driver: bridge
    
